- name: 1-0001-16_PasswordRules - change PASS_MAX_DAYS
  lineinfile:
    dest: /etc/login.defs
    regexp: "^PASS_MAX_DAYS"
    insertafter: EOF
    line: "PASS_MAX_DAYS {{ base_base.ID.password_policy.max_days }}"
  when:
    - base_base.ID.password_policy.max_days is defined
   
- name: 1-0001-16_PasswordRules - change PASS_MIN_DAYS
  lineinfile:
    dest: /etc/login.defs
    regexp: "^PASS_MIN_DAYS"
    insertafter: EOF
    line: "PASS_MIN_DAYS {{ base_base.ID.password_policy.min_days }}"
  when:
    - base_base.ID.password_policy.min_days is defined

- name: 1-0001-16_PasswordRules - change PASS_MIN_LEN
  lineinfile:
    dest: /etc/login.defs
    regexp: "^PASS_MIN_LEN"
    insertafter: EOF
    line: "PASS_MIN_LEN {{ base_base.ID.password_policy.min_length }}"
  when:
    - base_base.ID.password_policy.min_length is defined

- name: 1-0001-16_PasswordRules - change PASS_WARN_AGE
  lineinfile:
    dest: /etc/login.defs
    regexp: "^PASS_WARN_AGE"
    insertafter: EOF
    line: "PASS_WARN_AGE {{ base_base.ID.password_policy.warn_age }}"
  when:
    - base_base.ID.password_policy.warn_age is defined

