---
- name: 1-0001-28_Keyboard - change keytable for rhel6
  lineinfile:
    dest: /etc/sysconfig/keyboard
    regexp: '^KEYTABLE'
    line: "KEYTABLE=\"{{ base_base.OSCORE.keyboard.keybord_locale }}\""
  notify:
    - server_restart_for_RHEL6
    - wait_for_SSH_port_down
    - wait_for_SSH_port_up
  when:
    - ansible_distribution_major_version == "6"
    - base_base.OSCORE.keyboard.keybord_locale is defined

- name: 1-0001-28_Keyboard - check keytable for rhel7
  shell: localectl status
  register: ret_pre
  changed_when: false
  when: 
    - ansible_distribution_major_version == "7"
    - base_base.OSCORE.keyboard is defined

- name: 1-0001-28_Keyboard - change keytable for rhel7
  shell: localectl --no-convert set-x11-keymap {{ base_base.OSCORE.keyboard.keybord_locale}}
  notify:
    - server_restart_for_RHEL7
    - wait_for_SSH_port_down
    - wait_for_SSH_port_up
  when: 
    - ansible_distribution_major_version == "7"
    - base_base.OSCORE.keyboard.keybord_locale is defined
    - ret_pre.stdout.find( "Layout{{':'}} {{ base_base.OSCORE.keyboard.keybord_locale }}" ) == -1

- name: 1-0001-28_Keyboard - post check keytable for rhel7
  shell: localectl --no-convert set-keymap {{ base_base.OSCORE.keyboard.keybord_locale }}
  notify:
    - server_restart_for_RHEL7
    - wait_for_SSH_port_down
    - wait_for_SSH_port_up
  when:
    - ansible_distribution_major_version == "7"
    - base_base.OSCORE.keyboard.keybord_locale is defined
    - ret_pre.stdout.find( "Keymap{{':'}} {{ base_base.OSCORE.keyboard.keybord_locale }}" ) == -1


