---
l0106_install_path: "{{ PrivateCA.install_path }}"

l0106_ca_cert:
  pem_filename: "{{ PrivateCA.ca_cert.pem_filename }}"
  der_filename: "{{ PrivateCA.ca_cert.der_filename }}"
  csr_filename: "{{ PrivateCA.ca_cert.csr_filename }}"
  csr_validity_term: "{{ PrivateCA.ca_cert.csr_validity_term }}"
  distinguished_name:
    country: "{{ PrivateCA.ca_cert.distinguished_name.country }}"
    state: "{{ PrivateCA.ca_cert.distinguished_name.state }}"
    locality_name: "{{ PrivateCA.ca_cert.distinguished_name.locality_name }}"
    organization: "{{ PrivateCA.ca_cert.distinguished_name.organization }}"
    unit_name: "{{ PrivateCA.ca_cert.distinguished_name.unit_name }}"
    common_name: "{{ PrivateCA.ca_cert.distinguished_name.common_name }}"
    email: "{{ PrivateCA.ca_cert.distinguished_name.email | default('') }}"
    challenge_pass: "{{ PrivateCA.ca_cert.distinguished_name.challenge_pass | default('') }}"
    optional_company: "{{ PrivateCA.ca_cert.distinguished_name.optional_company | default('') }}"
  private_key_filename: "{{ PrivateCA.ca_cert.private_key_filename }}"
  private_key_length: "{{ PrivateCA.ca_cert.private_key_length }}" 
  private_key_passphrase: "{{ PrivateCA.ca_cert.private_key_passphrase }}"
  hash_algorithm: "{{ PrivateCA.ca_cert.hash_algorithm }}"

