---
- name: 2-9901-03_ApplyHotfix_pre
  raw: if ((Get-HotFix).Length -ne 0){(Get-Hotfix).HotfixID.Contains('KB{{ HOTFIX.ID }}')}
  register: ret_pre
  when:
    - install_hotfix == true
  changed_when: ret_pre.stdout != "True\r\n"
  always_run: yes
  notify: 
    - server_restart_for_Win
    - wait_for_WinRM_port_down
    - wait_for_WinRM_port_up

- name: 2-9901-03_ApplyHotfix_extract
  raw: wusa.exe '{{ remote_tmp_dir }}\{{ HOTFIX.FILE }}.msu' /extract:'{{ remote_tmp_dir }}' /quiet
  when:
    - install_hotfix == true
    - ret_pre | changed
  always_run: no

- name: 2-9901-03_ApplyHotfix_apply
  raw: dism.exe /online /add-package /PackagePath:'{{ remote_tmp_dir }}\{{ HOTFIX.FILE }}.cab' /quiet /norestart
  when:
    - install_hotfix == true
    - ret_pre | changed
  failed_when: false
  always_run: no

- meta: flush_handlers

- name: 2-9901-03_ApplyHotfix_post
  raw: if ((Get-HotFix).Length -ne 0){(Get-Hotfix).HotfixID.Contains('KB{{ HOTFIX.ID }}')}
  when:
    - install_hotfix == true
    - ret_pre.stdout != "True\r\n"
  register: ret_post
  failed_when: ret_post.stdout != "True\r\n"
  always_run: no

